# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  pkgs,
  ...
}:

{
  boot.initrd.kernelModules = [ ];
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "dm_mod"
    "dm_crypt"
  ];

  boot.kernelParams = [ ];
  boot.kernelModules = [
    "kvm-amd"
    "snd_seq"
  ];

  hardware.firmware = with pkgs; [
    linux-firmware
    alsa-firmware
  ];

  fileSystems."crypted" = {
    device = "/dev/disk/by-uuid/635797a9-367d-48c9-bd96-c23caf4bfbe3";
    fsType = "luks";
    neededForBoot = true;
    options = [ "--debug" ];
  };

  fileSystems."/" = {
    device = "/dev/mapper/crypted";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CAF2-A3A9";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/disk1" = {
    device = "/dev/disk/by-uuid/4AD277B9D277A839";
    fsType = "ntfs3";
  };

  fileSystems."/mnt/disk2" = {
    device = "/dev/disk/by-uuid/dc514686-c1e3-4235-95b0-8accb8a7b129";
    fsType = "ext4";
  };

  swapDevices = [ ];

  # maybe this will work... someday
  programs.limine.extraEntries = ''
    /+Arch Linux
      //GRUB: Arch Linux
        protocol: efi
        path: uuid(bd1a0932-9169-414f-84bf-5a76264ef829):/EFI/grub/grubx64.efi
  '';

}
