# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  pkgs,
  ...
}:

{
  boot.initrd.kernelModules = [ ];
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "dm_mod"
    "dm_crypt"
  ];

  boot.kernelParams = [ ];
  boot.kernelModules = [
    "kvm-amd"
    "snd_seq"
  ];

  hardware.firmware = with pkgs; [
    linux-firmware
    ipw2200-firmware
    rtl8192su-firmware
    rt5677-firmware
    rtl8761b-firmware
    zd1211fw
    alsa-firmware
    sof-firmware
    libreelec-dvb-firmware
  ];

  fileSystems."crypted" = {
    device = "/dev/disk/by-uuid/635797a9-367d-48c9-bd96-c23caf4bfbe3";
    fsType = "luks";
    neededForBoot = true;
    options = [ "--timeout 60" ];
  };

  fileSystems."/" = {
    device = "/dev/mapper/crypted";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CAF2-A3A9";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/disk1" = {
    device = "/dev/disk/by-uuid/4AD277B9D277A839";
    fsType = "ntfs3";
  };

  fileSystems."/mnt/disk2" = {
    device = "/dev/disk/by-uuid/dc514686-c1e3-4235-95b0-8accb8a7b129";
    fsType = "ext4";
  };

  swapDevices = [ ];

  programs.limine.extraEntries = ''
    /+Arch Linux
      //Arch Linux
        protocol: linux
        kernel_path: guid(a1462fcd-734d-47c6-b114-0f743dc799a4):/boot/vmlinuz-linux
        module_path: guid(a1462fcd-734d-47c6-b114-0f743dc799a4):/boot/initramfs-linux.img
        module_path: guid(a1462fcd-734d-47c6-b114-0f743dc799a4):/boot/amd-ucode.img
        cmdline: root=UUID=a1462fcd-734d-47c6-b114-0f743dc799a4 rw loglevel=3 amd_iommu=on iommu=pt amdgpu.dcdebugmask=0x12

      //Arch Linux LTS
        protocol: linux
        kernel_path: guid(a1462fcd-734d-47c6-b114-0f743dc799a4):/boot/vmlinuz-linux-lts
        module_path: guid(a1462fcd-734d-47c6-b114-0f743dc799a4):/boot/initramfs-linux-lts.img
        module_path: guid(a1462fcd-734d-47c6-b114-0f743dc799a4):/boot/amd-ucode.img
        cmdline: root=UUID=a1462fcd-734d-47c6-b114-0f743dc799a4 rw loglevel=3 amd_iommu=on iommu=pt amdgpu.dcdebugmask=0x12
  '';

}
