# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
    "dm_mod"
    "dm_crypt"
  ];
  boot.initrd.kernelModules = [ ];

  # TODO monitor https://github.com/finix-community/finix/pull/69
  # boot.initrd.emergencyAccess = true;

  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  hardware.firmware = with pkgs; [
    linux-firmware
    ipw2200-firmware
    rtl8192su-firmware
    rt5677-firmware
    rtl8761b-firmware
    zd1211fw
    alsa-firmware
    sof-firmware
    libreelec-dvb-firmware
  ];

  fileSystems."/" = {
    device = "/dev/mapper/crypted";
    fsType = "ext4";
  };

  fileSystems."crypted" = {
    device = "/dev/disk/by-uuid/44e57707-0cc7-4305-a323-9b4d1fafa454";
    fsType = "luks";
    neededForBoot = true;
    options = [ "--allow-discards" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/38D0-460C";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/c4ce02d2-e6dd-4058-b0c7-9737f6772094"; }
  ];
}
