# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
    "dm_mod"
    "dm_crypt"
  ];
  boot.initrd.kernelModules = [ ];

  # TODO monitor https://github.com/finix-community/finix/pull/69
  # boot.initrd.emergencyAccess = true;

  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  hardware.firmware = with pkgs; [
    linux-firmware
    ipw2200-firmware
    rtl8192su-firmware
    rt5677-firmware
    rtl8761b-firmware
    zd1211fw
    alsa-firmware
    sof-firmware
    libreelec-dvb-firmware
  ];

  fileSystems."/" = {
    device = "/dev/mapper/crypted";
    fsType = "ext4";
  };

  fileSystems."crypted" = {
    device = "/dev/disk/by-uuid/5f2c994b-cd38-408d-8f61-ec046106d40d";
    fsType = "luks";
    neededForBoot = true;
    options = [ "--allow-discards" ];
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1B3E-2B97";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e9c75a72-fdb1-4c65-aa81-4abd6d6e6edd"; }
    ];
}
